apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "a353962dfb519478f98ed83376937d09-1314709390.eu-west-3.elb.amazonaws.com"
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: hello-v1-svc
            port:
              number: 80
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: hello-v2-svc
            port:
              number: 80
