name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS EKS
        uses: giovannirossini/aws-eks@v2.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-3"
          cluster-name: "ClusterGitHubActions"
          kubectl-version: "1.27"
          command: |
            kubectl apply -f ./01-hello-app-deployment-v1.yaml
            kubectl apply -f ./02-hello-app-deployment-v2.yaml
            kubectl apply -f ./03-hello-svc-v1.yaml
            kubectl apply -f ./04-hello-svc-v2.yaml
            kubectl apply -f ./05-ingress.yaml
