name: Deploy to AWS EKS
on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3
      - uses: actions/checkout@v2
      - name: Run kubectl
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: |
            "apply 01-hello-app-deployment-v1.yaml"
            "apply 02-hello-app-deployment-v2.yaml"
            "apply 03-hello-svc-v1.yaml"
            "apply 04-hello-svc-v2.yaml"
            "apply 05-ingress.yaml"
        env:
          EKS_CLUSTER: ClusterGitHubActions



          
